export const pricingOptions = [
  {
    id: 1,
    forBusiness: false,
    name: 'Standard',
    price: '100 kr',
    description: 'For those who want to let Globy kick-start the journey.',
    subscribeUrl: '/#',
    benefits: [
      {
        title: 'Globy assistans',
        isSupported: true,
      },
      {
        title: 'Content creation',
        isSupported: false,
      },
      {
        title: 'Unlimited changes',
        isSupported: false,
      },
      {
        title: 'Social media coverage',
        isSupported: false,
      },
    ],
  },
  {
    id: 2,
    forBusiness: false,
    name: 'PRO',
    price: '200 kr',
    description: 'For those who want to take their business to the next level.',
    subscribeUrl: '/#',
    benefits: [
      {
        title: 'Globy assistans',
        isSupported: true,
      },
      {
        title: 'Content creation',
        isSupported: true,
      },
      {
        title: 'Unlimited changes',
        isSupported: false,
      },
      {
        title: 'Social media coverage',
        isSupported: false,
      },
    ],
  },
  {
    id: 3,
    forBusiness: true,
    name: 'BUSINESS',
    price: '300 kr',
    description: 'For those who want to become a global star.',
    subscribeUrl: '/#',
    benefits: [
      {
        title: 'Globy assistans',
        isSupported: true,
      },
      {
        title: 'Content creation',
        isSupported: true,
      },
      {
        title: 'Unlimited changes',
        isSupported: true,
      },
      {
        title: 'Social media coverage',
        isSupported: true,
      },
    ],
  },
]

export const industries = [
  { label: 'Real estate brokers', value: 'Real estate brokers' },
  { label: 'Construction', value: 'Construction' },
  { label: 'Law', value: 'Law' },
  { label: 'Logistics', value: 'Logistics' },
  { label: 'Insurance', value: 'Insurance' },
  { label: 'Finance', value: 'Finance' },
  { label: 'Marketing', value: 'Marketing' },
  { label: 'It consultancy', value: 'It consultancy' },
  { label: 'Energy', value: 'Energy' },
  { label: 'Design', value: 'Design' },
  { label: 'Consultancy', value: 'Consultancy' },
  { label: 'Web development', value: 'Web development' },
  { label: 'Healthcare', value: 'Healthcare' },
  { label: 'Media', value: 'Media' },
  { label: 'Technology', value: 'Technology' },
  { label: 'Politics', value: 'Politics' },
  { label: 'Culture', value: 'Culture' },
  { label: 'Animal care', value: 'Animal care' },
  { label: 'Events', value: 'Events' },
  { label: 'Transportation', value: 'Transportation' },
  { label: 'Social services', value: 'Social services' },
  { label: 'Photography', value: 'Photography' },
  { label: 'Restaurants', value: 'Restaurants' },
  { label: 'Traveling', value: 'Traveling' },
  { label: 'Entertainment', value: 'Entertainment' },
  { label: 'Hospitality', value: 'Hospitality' },
  { label: 'Security', value: 'Security' },
  { label: 'Manufacturing industry', value: 'Manufacturing industry' },
  { label: 'Health', value: 'Health' },
  { label: 'Farming', value: 'Farming' },
  { label: 'Automotive', value: 'Automotive' },
  { label: 'Agriculture', value: 'Agriculture' },
  { label: 'Music', value: 'Music' },
  { label: 'Art', value: 'Art' },
  { label: 'Education', value: 'Education' },
  { label: 'Coaching', value: 'Coaching' },
  { label: 'Non profit', value: 'Non profit' },
  { label: 'Fitness', value: 'Fitness' },
  { label: 'Printing', value: 'Printing' },
  { label: 'Sport', value: 'Sport' },
  { label: 'Wellness', value: 'Wellness' },
  { label: 'Home decor', value: 'Home decor' },
  { label: 'Community', value: 'Community' },
  { label: 'Nonprofit', value: 'Nonprofit' },
  { label: 'Religion', value: 'Religion' },
  { label: 'Electronics', value: 'Electronics' },
  { label: 'Furniture', value: 'Furniture' },
  { label: 'Beauty', value: 'Beauty' },
  { label: 'Recruitment', value: 'Recruitment' },
  { label: 'Food', value: 'Food' },
  { label: 'Wine', value: 'Wine' },
  { label: 'Veterinary', value: 'Veterinary' },
  { label: 'Plumbing', value: 'Plumbing' },
  { label: 'Architecture', value: 'Architecture' },
  { label: 'Dentists', value: 'Dentists' },
  { label: 'Accounting', value: 'Accounting' },
  { label: 'Video production', value: 'Video production' },
  { label: 'Engineering', value: 'Engineering' },
  { label: 'Film', value: 'Film' },
  { label: 'Graphical design', value: 'Graphical design' },
  { label: 'Mining', value: 'Mining' },
  { label: 'Electrical', value: 'Electrical' },
  { label: 'Social media', value: 'Social media' },
  { label: 'Communication', value: 'Communication' },
  { label: 'Car workshops', value: 'Car workshops' },
  { label: 'Dentistry', value: 'Dentistry' },
  { label: 'Landscaping', value: 'Landscaping' },
  { label: 'Digital marketing', value: 'Digital marketing' },
  { label: 'Legal', value: 'Legal' },
  { label: 'Services', value: 'Services' },
  { label: 'Real estate', value: 'Real estate' },
  { label: 'Property management', value: 'Property management' },
  { label: 'Environment', value: 'Environment' },
  { label: 'Interior design', value: 'Interior design' },
  { label: 'Creative', value: 'Creative' },
  { label: 'Software', value: 'Software' },
  { label: 'Cleaning', value: 'Cleaning' },
  { label: 'Hotel', value: 'Hotel' },
  { label: 'Research', value: 'Research' },
  { label: 'Hvac', value: 'Hvac' },
  { label: 'Gaming', value: 'Gaming' },
  { label: 'Hair saloons', value: 'Hair saloons' },
  { label: 'Lifestyle', value: 'Lifestyle' },
  { label: 'Gardening stores', value: 'Gardening stores' },
  { label: 'Transport', value: 'Transport' },
  { label: 'Telecommunications', value: 'Telecommunications' },
  { label: 'Environmental', value: 'Environmental' },
  { label: 'Recycling', value: 'Recycling' },
  { label: 'Retail', value: 'Retail' },
  { label: 'Literature', value: 'Literature' },
  { label: 'Aviation', value: 'Aviation' },
  { label: 'Gardening', value: 'Gardening' },
  { label: 'Textiles', value: 'Textiles' },
  { label: 'Charity', value: 'Charity' },
  { label: 'Social', value: 'Social' },
  { label: 'Rental', value: 'Rental' },
  { label: 'Dance', value: 'Dance' },
  { label: 'Catering', value: 'Catering' },
  { label: 'Fashion', value: 'Fashion' },
  { label: 'Accommodation', value: 'Accommodation' },
  { label: 'Packaging', value: 'Packaging' },
  { label: 'Tourism', value: 'Tourism' },
  { label: 'Training', value: 'Training' },
  { label: 'Beverages', value: 'Beverages' },
  { label: 'Jewelry', value: 'Jewelry' },
]
